# **Shallow Copy and Deep Copy**

In [ ]:
import numpy as np

In [ ]:
a = np.arange(4)

a
b=a
b

array([0, 1, 2, 3])

In [ ]:
a[0] = 100
b

array([100,   1,   2,   3])

In [ ]:
id(a)

137021822812048

In [ ]:
id(b)

137021822812048

In [ ]:
np.shares_memory(a, b) # they're both pointing to same location in RAM

True

In [ ]:
b = a.reshape(2, 2)
b

array([[100,   1],
       [  2,   3]])

In [ ]:
a

array([100,   1,   2,   3])

In [ ]:
print(id(a), id(b)) #id is changed

137021822909488 137021823027120


In [ ]:
np.shares_memory(a, b) # the data in RAM didn't change,
# only the header file of the numpy array changed

True

In [ ]:
b[0][1]=12
b

array([[100,  12],
       [  2,   3]])

In [ ]:
a

array([100,  12,   2,   3])

In [ ]:
b = 'A'
a

array([100,   1,   2,   3])

In [ ]:
b

'A'

In [ ]:
np.shares_memory(a, b)

False

In [ ]:
# reshaping an array, doesn't CREATE a new array.
a


array([100,  12,   2,   3])

In [ ]:
c = a + 2
c

array([102,  14,   4,   5])

In [ ]:
a[0] = 50
c

array([102,  14,   4,   5])

In [ ]:
np.shares_memory(c, a)

False

In [ ]:
c = a + 0
c

array([50, 12,  2,  3])

 Any arithmetic operation, masking or changing in datatype, it will create
 new array

In [ ]:
a= np.arange(10)
a


b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
  b = a[a % 1 == 0]
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_shallow_copy = a.view()

b = a.view() or b = a  both are same but different syntax

In [ ]:
## Deep copy

b = a.copy()

In [ ]:
np.shares_memory(a, b)

False

# **Edge Case Object array Numpy**

In [ ]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8]], dtype='object')
# in general very wrong way of coding, you shouldn't never use, unless you've a good reason.


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [ ]:
arr = np.array([1, 'm', [1,2,3]], dtype = 'object')
arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
copy_arr = arr.copy() # should do a deep copy in general, but here it doesn't
copy_arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
copy_arr[2][0] = 999
copy_arr

array([1, 'm', list([999, 2, 3])], dtype=object)

In [ ]:
arr

array([1, 'm', list([999, 2, 3])], dtype=object)

In [ ]:
from copy import deepcopy

copy = deepcopy(arr)
copy[2][0] = 111
arr

array([1, 'm', list([999, 2, 3])], dtype=object)

# **Array Splitting**

In [ ]:
x = np.arange(9)
np.split(x, 2)

ValueError: array split does not result in an equal division

The value that we proivde in split fuction for spliting that should be divisiable by array

In [ ]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]

In [ ]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
# Splitting on the basis of exact indices

c = np.arange(16)
np.split(c, [3, 5, 6])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [ ]:
# np.hsplit

x = np.arange(16.0).reshape(4, 4)

x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [ ]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [ ]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [ ]:
np.hsplit(x, np.array([4, 5]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]),
 array([], shape=(4, 0), dtype=float64),
 array([], shape=(4, 0), dtype=float64)]

# **Stacking**

In [ ]:
a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)
a

array([1, 2, 3, 4])

In [ ]:
b

array([2, 3, 4, 5])

In [ ]:
c

array([3, 4, 5, 6])

In [ ]:
np.vstack([b, c, a])

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [ ]:
a = np.arange(1, 5)
b = np.arange(2, 4)
c = np.arange(3, 10)

np.vstack([b, c, a]) #the array should be same size to do stacking

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 7

In [ ]:
#hstack

a = np.arange(5).reshape(5, 1)
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
b = np.arange(15).reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(a, '\n\n', b)
np.vstack((a, b))

[[1]
 [2]
 [3]] 

 [[4]
 [5]
 [6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# np.concatenate

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a, b], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])

np.concatenate([a, b], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(1, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])

np.concatenate([a, b], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [ ]:
a = np.arange(6).reshape(3, 2)
b = np.arange(9).reshape(3, 3)

print(a, '\n\n', b)

[[0 1]
 [2 3]
 [4 5]] 

 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.concatenate([a, b], axis=1)

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([[5, 6]])
b

[[1 2]
 [3 4]]


array([[5, 6]])

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate([a, b.T], axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.linspace(0, 100, num=1000)

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

In [ ]:
arr = np.array([[[1, 2, 3, 4, 5], [3, 4, 6, 7, 8]], [[5, 6, 6, 7, 8], [7, 8, 3, 4, 5]]])
# result = arr[:, 1, 0]
result = arr[:, 1, 0]
result

array([3, 7])

In [ ]:
arr

array([[[1, 2, 3, 4, 5],
        [3, 4, 6, 7, 8]],

       [[5, 6, 6, 7, 8],
        [7, 8, 3, 4, 5]]])

In [ ]:
arr= np.array([[1,2],[3,4],[5,6]])

In [ ]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# .Firstly we will stack the arrays vertically, during which we will stack the matrix mat with [0]*m for the upper and lower boundaries.

#During vstack(), the number of columns of the two matrices used should be equal which is m here.

#2.Then we will stack the newer stacked matrix intmdt_mat2(result of step-1) horizontally, during which we will stack the arrays np.array([0]*(n+2)) and intmdt_mat2 for the left and right boundaries.#

In [ ]:
n=[0]*4

In [ ]:
n

[0, 0, 0]

In [ ]:
arr.shape


(3, 2)

In [ ]:
y= [[0]]*3

In [ ]:
y

[[0], [0], [0]]

In [ ]:
r= np.hstack((y,arr,y))

In [ ]:
r

array([[0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0]])

In [ ]:
np.vstack((n,np.hstack((y,arr,y)),n))

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

In [ ]:
n,m=arr.shape

In [ ]:
n

3

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
np.hstack((arr, arr[:, 0])).shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
arr[:, 0]

array([1, 4, 7])

In [ ]:
np.hstack((arr, arr[:, [0]])).shape

(3, 4)

In [ ]:
arr[:, [0]]

array([[1],
       [4],
       [7]])

In [ ]:
np.hstack((arr, arr[:, [0]])).shape

(3, 4)

In [ ]:
a= np.array([[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hsplit(a, [2,3,4])[:-1]

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [ ]:
arr = np.array([[[0, 1],
             [2, 3]],

            [[4, 5],
             [6, 7]]])

In [ ]:
arr[:, 0:,:1]

array([[[0],
        [2]],

       [[4],
        [6]]])

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

In [ ]:
data=np.dsplit(data,2)

[array([[10, 20, 30],
        [40, 50, 60]]),
 array([[ 70,  80,  90],
        [100, 110, 120]])]

In [ ]:
data[-1]

array([100, 110, 120])