In [6]:
import numpy as np

In [1]:
a=[1,2,3,"Jeevan",True]
a

[1, 2, 3, 'Jeevan', True]

In [2]:
a=[1,2,3,4,5,6,7,8]

In [5]:
res=[i**2 for i in a]


In [11]:
b=np.array(a)


In [13]:
l= range(1000000)
l

range(0, 1000000)

In [15]:
%timeit [i**2 for i in l]


305 ms ± 59.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
l=np.array(range(1000000))

In [21]:
l.shape

(1000000,)

In [22]:
l.ndim

1

In [25]:
arr2=np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [6,7,8,9,0]])

%timeit l**2

In [26]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
 arr=np.arange(5)
 arr

array([0, 1, 2, 3, 4])

In [5]:
 arr3=np.arange(5,10,0.5)
 arr3


array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [7]:
arr[2:4]=0
arr

array([0, 1, 0, 0, 4])

Type Conversion

In [7]:
arr4=np.array([1,2,3,4,5])
arr4

array([1, 2, 3, 4, 5])

In [9]:
arr5=np.array([1,2,3,4,5,8.0])
arr5

array([1., 2., 3., 4., 5., 8.])

In [10]:
arr5=np.array([1,2,3,4,5,8.0], dtype='int')
arr5

array([1, 2, 3, 4, 5, 8])

In [16]:
arr5=np.array([1,2,3,4,5,8.0], dtype='str')
arr5

array(['1', '2', '3', '4', '5', '8.0'], dtype='<U3')

In [13]:
arr5=np.array(["Jeevan",2,3,4,5,8.0], dtype='int')
arr5

TypeError: data type 'int ' not understood

In [23]:
arr6=np.array([10,20,30,40,50])
arr6.astype('float64')

array([10., 20., 30., 40., 50.])

In [15]:
arr4

array([1, 2, 3, 4, 5])

In [17]:

arr4[[2,4,-1]]

array([3, 5, 5])

In [18]:
arr4[:3]

array([1, 2, 3])

In [21]:
arr4[-4:1:-1]

array([], dtype=int64)

In [22]:
arr4>3

array([False, False, False,  True,  True])

In [23]:
arr4[arr4<3]

array([1, 2])